import { Montserrat } from "next/font/google";
import { TopExchange } from "@/widgets/top-exchange";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export default function SellLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      {children}
      <TopExchange />
    </div>
  );
}
