// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

import { BlogBanner } from "@/widgets/blog";

export default async function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <BlogBanner />
      {children}
    </div>
  );
}
