export enum routes {
  home = "/",
  about = "/about",
  partners = "/partners",
  help = "/help",
  blog = "/blog",
  category = "/category",
  tag = "/tag",
  article = "/article",
  exchangers = "/crypto-exchangers",
  questions = "/questions",
  contacts = "/contacts",
  exchange = "/exchange",
  buy = "/buy",
  sell = "/sell",
}
