export enum routes {
  home = "/",
  about = "/about",
  partners = "/for-partners",
  help_article = "/help?article=true",
  help_faq = "/help",
  blog = "/blog",
  category = "/category",
  tag = "/tag",
  article = "/article",
  exchangers = "/crypto-exchangers",
  questions = "/questions",
  contacts = "/contacts",
  exchange = "/exchange",
  sitemap = "/sitemap",
  directions = "/sitemap/directions",
}
