import { CryptoTableColumns } from "./columns";

export const mockData: CryptoTableColumns[] = [
  {
    info: {
      name: "John Doe",
      age: "30",
      amountReserves: 150000,
      country: {
        id: 1,
        name: { ru: "Россия", en: "Russia" },
        icon_url: "https://example.com/icons/russia.png",
      },
    },
    exchangerName: "BestExchange",
    workStatus: "Active",
    reserves: 100000,
    courses: 12.34,
    reviews: { positive: 120, neutral: 5, negative: 3 },
  },
  {
    info: {
      name: "Jane Smith",
      age: "25",
      amountReserves: 200000,
      country: {
        id: 2,
        name: { ru: "США", en: "USA" },
        icon_url: "https://example.com/icons/usa.png",
      },
    },
    exchangerName: "QuickSwap",
    workStatus: "Active",
    reserves: 180000,
    courses: 15.67,
    reviews: { positive: 210, neutral: 10, negative: 4 },
  },
  {
    info: {
      name: "Alexander Ivanov",
      age: "45",
      amountReserves: 300000,
      country: {
        id: 3,
        name: { ru: "Канада", en: "Canada" },
        icon_url: "https://example.com/icons/canada.png",
      },
    },
    exchangerName: "SafeEx",
    workStatus: "Inactive",
    reserves: 250000,
    courses: 11.23,
    reviews: { positive: 320, neutral: 15, negative: 8 },
  },
  {
    info: {
      name: "Maria Garcia",
      age: "32",
      amountReserves: 120000,
      country: {
        id: 4,
        name: { ru: "Испания", en: "Spain" },
        icon_url: "https://example.com/icons/spain.png",
      },
    },
    exchangerName: "CryptoSecure",
    workStatus: "Active",
    reserves: 90000,
    courses: 9.45,
    reviews: { positive: 110, neutral: 2, negative: 1 },
  },
  {
    info: {
      name: "Michael Johnson",
      age: "40",
      amountReserves: 220000,
      country: {
        id: 5,
        name: { ru: "Германия", en: "Germany" },
        icon_url: "https://example.com/icons/germany.png",
      },
    },
    exchangerName: "FastChange",
    workStatus: "Active",
    reserves: 200000,
    courses: 14.89,
    reviews: { positive: 150, neutral: 6, negative: 2 },
  },
  {
    info: {
      name: "Sophie Lee",
      age: "28",
      amountReserves: 175000,
      country: {
        id: 6,
        name: { ru: "Южная Корея", en: "South Korea" },
        icon_url: "https://example.com/icons/south_korea.png",
      },
    },
    exchangerName: "TrustExchange",
    workStatus: "Inactive",
    reserves: 160000,
    courses: 13.57,
    reviews: { positive: 300, neutral: 20, negative: 5 },
  },
  {
    info: {
      name: "Luca Rossi",
      age: "35",
      amountReserves: 240000,
      country: {
        id: 7,
        name: { ru: "Италия", en: "Italy" },
        icon_url: "https://example.com/icons/italy.png",
      },
    },
    exchangerName: "CoinSafe",
    workStatus: "Active",
    reserves: 210000,
    courses: 16.78,
    reviews: { positive: 130, neutral: 8, negative: 6 },
  },
  {
    info: {
      name: "Emily Davis",
      age: "27",
      amountReserves: 190000,
      country: {
        id: 8,
        name: { ru: "Франция", en: "France" },
        icon_url: "https://example.com/icons/france.png",
      },
    },
    exchangerName: "ExchangeNow",
    workStatus: "Active",
    reserves: 180000,
    courses: 10.45,
    reviews: { positive: 290, neutral: 9, negative: 7 },
  },
  {
    info: {
      name: "Yuki Tanaka",
      age: "33",
      amountReserves: 165000,
      country: {
        id: 9,
        name: { ru: "Япония", en: "Japan" },
        icon_url: "https://example.com/icons/japan.png",
      },
    },
    exchangerName: "CryptoQuick",
    workStatus: "Inactive",
    reserves: 150000,
    courses: 12.67,
    reviews: { positive: 180, neutral: 3, negative: 2 },
  },
  {
    info: {
      name: "Olivia Brown",
      age: "29",
      amountReserves: 230000,
      country: {
        id: 10,
        name: { ru: "Австралия", en: "Australia" },
        icon_url: "https://example.com/icons/australia.png",
      },
    },
    exchangerName: "SwiftEx",
    workStatus: "Active",
    reserves: 220000,
    courses: 18.23,
    reviews: { positive: 210, neutral: 7, negative: 4 },
  },
  {
    info: {
      name: "Liam Wilson",
      age: "31",
      amountReserves: 210000,
      country: {
        id: 11,
        name: { ru: "Великобритания", en: "United Kingdom" },
        icon_url: "https://example.com/icons/uk.png",
      },
    },
    exchangerName: "QuickSwap",
    workStatus: "Active",
    reserves: 190000,
    courses: 15.45,
    reviews: { positive: 175, neutral: 4, negative: 3 },
  },
  {
    info: {
      name: "Ava Martinez",
      age: "26",
      amountReserves: 180000,
      country: {
        id: 12,
        name: { ru: "Мексика", en: "Mexico" },
        icon_url: "https://example.com/icons/mexico.png",
      },
    },
    exchangerName: "CryptoPlus",
    workStatus: "Inactive",
    reserves: 160000,
    courses: 11.23,
    reviews: { positive: 160, neutral: 5, negative: 3 },
  },
  {
    info: {
      name: "Noah Thomas",
      age: "34",
      amountReserves: 250000,
      country: {
        id: 13,
        name: { ru: "Бразилия", en: "Brazil" },
        icon_url: "https://example.com/icons/brazil.png",
      },
    },
    exchangerName: "SafeTrade",
    workStatus: "Active",
    reserves: 230000,
    courses: 17.89,
    reviews: { positive: 200, neutral: 10, negative: 6 },
  },
  {
    info: {
      name: "Isabella Hernandez",
      age: "36",
      amountReserves: 220000,
      country: {
        id: 14,
        name: { ru: "Аргентина", en: "Argentina" },
        icon_url: "https://example.com/icons/argentina.png",
      },
    },
    exchangerName: "SecureExchange",
    workStatus: "Active",
    reserves: 200000,
    courses: 13.45,
    reviews: { positive: 140, neutral: 6, negative: 2 },
  },
  {
    info: {
      name: "Ethan Nguyen",
      age: "39",
      amountReserves: 240000,
      country: {
        id: 15,
        name: { ru: "Вьетнам", en: "Vietnam" },
        icon_url: "https://example.com/icons/vietnam.png",
      },
    },
    exchangerName: "CryptoFast",
    workStatus: "Inactive",
    reserves: 220000,
    courses: 14.78,
    reviews: { positive: 180, neutral: 8, negative: 5 },
  },
  {
    info: {
      name: "Sophia Kim",
      age: "38",
      amountReserves: 170000,
      country: {
        id: 16,
        name: { ru: "Южная Корея", en: "South Korea" },
        icon_url: "https://example.com/icons/south_korea.png",
      },
    },
    exchangerName: "ChangeNow",
    workStatus: "Active",
    reserves: 150000,
    courses: 12.34,
    reviews: { positive: 220, neutral: 11, negative: 3 },
  },
  {
    info: {
      name: "William Brown",
      age: "29",
      amountReserves: 200000,
      country: {
        id: 17,
        name: { ru: "ЮАР", en: "South Africa" },
        icon_url: "https://example.com/icons/south_africa.png",
      },
    },
    exchangerName: "QuickCrypto",
    workStatus: "Active",
    reserves: 180000,
    courses: 15.67,
    reviews: { positive: 130, neutral: 4, negative: 2 },
  },
  {
    info: {
      name: "Emma White",
      age: "27",
      amountReserves: 140000,
      country: {
        id: 18,
        name: { ru: "Испания", en: "Spain" },
        icon_url: "https://example.com/icons/spain.png",
      },
    },
    exchangerName: "FastChange",
    workStatus: "Inactive",
    reserves: 120000,
    courses: 10.89,
    reviews: { positive: 200, neutral: 3, negative: 1 },
  },
  {
    info: {
      name: "James Davis",
      age: "41",
      amountReserves: 210000,
      country: {
        id: 19,
        name: { ru: "Швейцария", en: "Switzerland" },
        icon_url: "https://example.com/icons/switzerland.png",
      },
    },
    exchangerName: "CryptoTrust",
    workStatus: "Active",
    reserves: 190000,
    courses: 18.45,
    reviews: { positive: 310, neutral: 12, negative: 4 },
  },
  {
    info: {
      name: "Charlotte Clark",
      age: "37",
      amountReserves: 160000,
      country: {
        id: 20,
        name: { ru: "Новая Зеландия", en: "New Zealand" },
        icon_url: "https://example.com/icons/new_zealand.png",
      },
    },
    exchangerName: "ExchangePro",
    workStatus: "Active",
    reserves: 140000,
    courses: 13.78,
    reviews: { positive: 150, neutral: 5, negative: 3 },
  },
];
