import { Montserrat } from "next/font/google";
import styles from "./layout.module.scss";
import "../src/shared/styles/globals.scss";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className={styles.container}>
        <Header />
        <main className={styles.body}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
