export enum StrapiCollectionNames {
  article = "blog-article",
  category = "blog-article-category",
  tag = "blog-article-tag",
  topic = "blog-article-topic",
  faq = "main-faq",
  about = "about-us",
  partner = "for-partner",
  help = "help-page-article",
  vedPage = "ved-page",
  vedAgent = "ved-agent",
  vcPage = "vc-page",
  virtualCard = "virtual-card",
  esimPage = "esim-page",
  eSim = "e-sim",
  // Справочники: на фронт приезжают только внутри агентов/карт/eSIM (populate),
  // но редактируются как отдельные сущности, поэтому тоже должны сбрасывать кэш списков.
  vedLabel = "ved-label",
  vedReview = "ved-review",
  vedCountry = "ved-country",
  vedCurrency = "ved-currency",
  esimLabel = "esim-label",
  esimReview = "esim-review",
  esimPaymentSystem = "esim-payment-system",
  vcPlatform = "vc-platform",
  vcPaymentSystem = "vc-payment-system",
  vcReview = "vc-review",
  // Разделы-рейтинги: оплата сервисов, карты, кредиты, микрозаймы
  paymentService = "payment-service",
  paymentServicePage = "payment-service-page",
  debitCard = "debit-card",
  debitCardPage = "debit-card-page",
  creditCard = "credit-card",
  creditCardPage = "credit-card-page",
  bankCredit = "bank-credit",
  bankCreditPage = "bank-credit-page",
  microloan = "microloan",
  microloanPage = "microloan-page",
  // Их справочники
  bank = "bank",
  cardFeature = "card-feature",
  cardBonus = "card-bonus",
  mlIssueChannel = "ml-issue-channel",
  mlCollection = "ml-collection",
}
