export enum StrapiCollectionNames {
  article = "blog-article",
  category = "blog-article-category",
  tag = "blog-article-tag",
  topic = "blog-article-topic",
  faq = "main-faq",
  about = "about-us",
  partner = "for-partner",
  help = "help-page-article",
  vedPage = "ved-page",
  vedAgent = "ved-agent",
  vcPage = "vc-page",
  virtualCard = "virtual-card",
  esimPage = "esim-page",
  eSim = "e-sim",
}
