import { Montserrat } from "next/font/google";
import { FAQ } from "@/widgets/faq";
import { SeoFooterText } from "@/widgets/seo-text";
import { SeoHeaderText } from "@/widgets/seo-text/header-text";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export default function SellLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: string;
}) {
  console.log(params);
  return (
    <div>
      <SeoHeaderText />
      {children}
      <FAQ />
      <SeoFooterText />
      Exchangers
    </div>
  );
}
